### ISSUE TITLE
Ameliorations de Novembre

### ISSUE THREAD

**Issue by unitrium** [nantral-platform/nantralPlatform#150]
Voici les axes de Novembre :

- [x] Passage en open #147 
- [x] Implementation du systeme de news #114 
- [ ] Communiquer aux respos de club
- [x] Amelioration DevOps : Backup DB sur S3 #38  Logs #146 
- [ ] Ameliorer certains champs de description d'events, de groupes et bientôt de news avec du richtext #145 
 
Quelques petites issues simples pour se lancer
-> Pour les nouveaux venus @tqdv  @samyhaff @Stormix 
#92 Ajout d'une option sur l'edit du profil pour choisir sa liste et la montrer sur son profil
#144 Un peu d'investigation avec ces comptes en double
#136 Simplement faire en sorte que si quelqu'un (les possesseurs d'iphone surtout) se connecte en mettant une majuscule dans son mail cela ne soit pas un pb
#139 Descriptions de clubs à revoir (c'est pas du code mais cela vous permet de vous familiariser avec l'interface admin)
